#
# List of available banks:
# https://auth.truelayer.com/api/providers/oauth/openbanking
# https://auth.truelayer.com/api/providers/oauth
#
banks:
- oauth-starling
- ob-barclays
- ob-bos
- ob-danske
- ob-first-direct
- ob-halifax
- ob-hsbc
- ob-hsbc-business
- ob-lloyds
- ob-lloyds-business
- ob-mbna
- ob-ms
- ob-monzo
- ob-nationwide
- ob-natwest
- ob-rbs
- ob-revolut
- ob-santander
- ob-tsb
- ob-tesco
- ob-ulster
